export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CLIAN_SERVICE_FIELD = 'CLIAN_SERVICE_FIELD'
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const FILTER_SERVICE = 'FILTER_SERVICE'